# Convolution Operations with Different Parameters

In [2]:
# importing the required librarires
import numpy as np
import tensorflow as tf

In [12]:
# Define the 5×5 input matrix
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]], dtype=np.float32)


In [14]:
# Define the 3×3 kernel
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]], dtype=np.float32)


In [16]:
# Function to perform convolution operation
def convolve2d(image, kernel, stride=1, padding='VALID'):
    image_h, image_w = image.shape
    kernel_h, kernel_w = kernel.shape
    
    if padding == 'SAME':
        pad_h = (kernel_h - 1) // 2
        pad_w = (kernel_w - 1) // 2
        padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    else:  # 'VALID' padding
        padded_image = image

    padded_h, padded_w = padded_image.shape
    output_h = (padded_h - kernel_h) // stride + 1
    output_w = (padded_w - kernel_w) // stride + 1
    output = np.zeros((output_h, output_w), dtype=np.float32)

    for i in range(0, output_h * stride, stride):
        for j in range(0, output_w * stride, stride):
            region = padded_image[i:i + kernel_h, j:j + kernel_w]
            if region.shape == kernel.shape:  # Ensure kernel fits
                output[i // stride, j // stride] = np.sum(region * kernel)
    
    return output

In [18]:
# Perform convolution operations with different strides and paddings
conv_valid_stride1 = convolve2d(input_matrix, kernel, stride=1, padding='VALID')
conv_same_stride1 = convolve2d(input_matrix, kernel, stride=1, padding='SAME')
conv_valid_stride2 = convolve2d(input_matrix, kernel, stride=2, padding='VALID')
conv_same_stride2 = convolve2d(input_matrix, kernel, stride=2, padding='SAME')

In [20]:
# Print output feature maps
print("Stride = 1, Padding = 'VALID'")
print(conv_valid_stride1, "\n")

print("Stride = 1, Padding = 'SAME'")
print(conv_same_stride1, "\n")

print("Stride = 2, Padding = 'VALID'")
print(conv_valid_stride2, "\n")

print("Stride = 2, Padding = 'SAME'")
print(conv_same_stride2, "\n")

Stride = 1, Padding = 'VALID'
[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]] 

Stride = 1, Padding = 'SAME'
[[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]] 

Stride = 2, Padding = 'VALID'
[[-6. -6.]
 [-6. -6.]] 

Stride = 2, Padding = 'SAME'
[[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]] 

